import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

// import * as Y from 'yjs'
// import { WebrtcProvider } from 'y-webrtc'

// const ydoc = new Y.Doc()
// // clients connected to the same room-name share document updates
// const provider = new WebrtcProvider('your-room-name', ydoc, { password: 'optional-room-password' })
// const yarray = ydoc.get('array', Y.Array)
